#!/usr/bin/env bash
#
# seed-workspaces.sh - Populate workspaces with test documents
#
# Usage:
#   ./scripts/seed-workspaces.sh [options]
#
# Options:
#   --scenario <name>   Scenario to generate (basic|migration|conflict|multi-author)
#   --count <n>         Number of documents to generate (default: 10)
#   --clean             Remove existing documents first
#   --workspace <name>  Target workspace (testing|docs|all) (default: all)
#   --help              Show this help message
#

set -e

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TESTING_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
WORKSPACES_DIR="${TESTING_DIR}/workspaces"

# Source document generator library
source "${SCRIPT_DIR}/lib/document-generator.sh"

# Default values
SCENARIO="basic"
COUNT=10
CLEAN=false
WORKSPACE="all"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --scenario)
            SCENARIO="$2"
            shift 2
            ;;
        --count)
            COUNT="$2"
            shift 2
            ;;
        --clean)
            CLEAN=true
            shift
            ;;
        --workspace)
            WORKSPACE="$2"
            shift 2
            ;;
        --help)
            head -n 20 "$0" | grep "^#" | sed 's/^# //; s/^#//'
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Validate scenario
case $SCENARIO in
    basic|migration|conflict|multi-author)
        ;;
    *)
        echo "Error: Invalid scenario '$SCENARIO'"
        echo "Valid scenarios: basic, migration, conflict, multi-author"
        exit 1
        ;;
esac

echo -e "${BLUE}=== Hermes Workspace Seeding ===${NC}"
echo -e "${BLUE}Scenario: ${SCENARIO}${NC}"
echo -e "${BLUE}Count: ${COUNT}${NC}"
echo -e "${BLUE}Workspace: ${WORKSPACE}${NC}"
echo ""

# Clean workspace if requested
if [ "$CLEAN" = true ]; then
    echo -e "${YELLOW}Cleaning existing documents...${NC}"
    
    if [ "$WORKSPACE" = "all" ] || [ "$WORKSPACE" = "testing" ]; then
        rm -rf "${WORKSPACES_DIR}/testing/"*
        echo -e "${GREEN}✅ Cleaned testing workspace${NC}"
    fi
    
    if [ "$WORKSPACE" = "all" ] || [ "$WORKSPACE" = "docs" ]; then
        rm -rf "${WORKSPACES_DIR}/docs/"*
        echo -e "${GREEN}✅ Cleaned docs workspace${NC}"
    fi
    
    echo ""
fi

# Create workspace directories
create_workspace_structure() {
    local workspace="$1"
    local base="${WORKSPACES_DIR}/${workspace}"
    
    ensure_dir "${base}/rfcs"
    ensure_dir "${base}/prds"
    ensure_dir "${base}/meetings"
    ensure_dir "${base}/drafts"
    ensure_dir "${base}/docs"
}

# Scenario: Basic
# Generate a variety of documents in testing workspace
scenario_basic() {
    echo -e "${BLUE}Generating basic test scenario...${NC}"
    
    local workspace="${WORKSPACES_DIR}/testing"
    create_workspace_structure "testing"
    
    # Generate RFCs
    local rfc_count=$((COUNT / 3))
    echo -e "${YELLOW}Generating ${rfc_count} RFCs...${NC}"
    for i in $(seq 1 $rfc_count); do
        local uuid=$(generate_uuid)
        local content=$(generate_rfc "$i" "$uuid" "Test RFC ${i}" "draft")
        write_document "${workspace}/rfcs/RFC-$(printf "%03d" "$i")-test-rfc.md" "$content"
    done
    
    # Generate PRDs
    local prd_count=$((COUNT / 3))
    echo -e "${YELLOW}Generating ${prd_count} PRDs...${NC}"
    for i in $(seq 1 $prd_count); do
        local uuid=$(generate_uuid)
        local content=$(generate_prd "$i" "$uuid" "Test Product ${i}" "draft")
        write_document "${workspace}/prds/PRD-$(printf "%03d" "$i")-test-product.md" "$content"
    done
    
    # Generate meeting notes
    local meeting_count=$((COUNT - rfc_count - prd_count))
    echo -e "${YELLOW}Generating ${meeting_count} meeting notes...${NC}"
    for i in $(seq 1 $meeting_count); do
        local uuid=$(generate_uuid)
        local content=$(generate_meeting_notes "$i" "$uuid" "Test Meeting ${i}")
        write_document "${workspace}/meetings/MEET-$(printf "%03d" "$i")-test-meeting.md" "$content"
    done
    
    # Create README
    cat > "${workspace}/README.md" <<EOF
# Testing Workspace

This workspace contains test documents generated by the Hermes seed script.

**Scenario**: Basic  
**Generated**: $(generate_timestamp)  
**Document Count**: ${COUNT}

## Structure

- \`rfcs/\` - Request for Comments documents
- \`prds/\` - Product Requirements Documents
- \`meetings/\` - Meeting notes
- \`drafts/\` - Draft documents
- \`docs/\` - Documentation

## Usage

These documents are automatically indexed by the Hermes indexer agent.

Access via:
- Web UI: http://localhost:4201
- API: http://localhost:8001/api/v2/documents
- Search: http://localhost:8001/api/v2/search

## Regeneration

To regenerate this workspace:

\`\`\`bash
cd testing
make seed-clean
\`\`\`
EOF
    
    echo -e "${GREEN}✅ Basic scenario complete${NC}"
}

# Scenario: Migration
# Create documents in both testing and docs workspaces with same UUIDs
scenario_migration() {
    echo -e "${BLUE}Generating migration test scenario...${NC}"
    
    create_workspace_structure "testing"
    create_workspace_structure "docs"
    
    # Generate documents with same UUID in both workspaces
    echo -e "${YELLOW}Generating ${COUNT} documents for migration...${NC}"
    for i in $(seq 1 $COUNT); do
        local uuid=$(generate_uuid)
        
        # Create in "source" workspace (docs) - simulate old location
        local source_content=$(generate_rfc "$i" "$uuid" "Migrating RFC ${i}" "published")
        write_document "${WORKSPACES_DIR}/docs/rfcs/RFC-$(printf "%03d" "$i")-migrating.md" "$source_content"
        
        # Create in "target" workspace (testing) - simulate new location
        # Slightly modify content to create potential conflict
        local target_content=$(generate_rfc "$i" "$uuid" "Migrating RFC ${i} - Updated" "draft")
        write_document "${WORKSPACES_DIR}/testing/rfcs/RFC-$(printf "%03d" "$i")-migrating.md" "$target_content"
        
        echo -e "${BLUE}  Created migration pair ${i}: UUID ${uuid}${NC}"
    done
    
    echo -e "${GREEN}✅ Migration scenario complete${NC}"
    echo -e "${YELLOW}Note: Documents with same UUID exist in both workspaces${NC}"
}

# Scenario: Conflict
# Create documents that will have conflicting content hashes
scenario_conflict() {
    echo -e "${BLUE}Generating conflict test scenario...${NC}"
    
    create_workspace_structure "testing"
    
    echo -e "${YELLOW}Generating ${COUNT} documents with version conflicts...${NC}"
    for i in $(seq 1 $COUNT); do
        local uuid=$(generate_uuid)
        
        # Create initial version
        local content_v1=$(generate_rfc "$i" "$uuid" "Conflict Test ${i}" "draft" "alice@example.com")
        local filepath="${WORKSPACES_DIR}/testing/rfcs/RFC-$(printf "%03d" "$i")-conflict.md"
        write_document "$filepath" "$content_v1"
        
        # Sleep briefly to ensure different timestamp
        sleep 0.1
        
        # Create a "conflicting" version by modifying the file
        # In real scenario, this would be from a different source
        local content_v2=$(generate_rfc "$i" "$uuid" "Conflict Test ${i} - MODIFIED" "review" "bob@example.com")
        
        # Save conflict marker
        cat >> "$filepath" <<EOF


---

## CONFLICT MARKER

This document has been modified to simulate a conflict scenario.

- **Original Author**: alice@example.com
- **Modified By**: bob@example.com  
- **Conflict Type**: Concurrent edit during migration

EOF
        
        echo -e "${BLUE}  Created conflict document ${i}: UUID ${uuid}${NC}"
    done
    
    echo -e "${GREEN}✅ Conflict scenario complete${NC}"
}

# Scenario: Multi-author
# Create documents from different authors with realistic timestamps
scenario_multi_author() {
    echo -e "${BLUE}Generating multi-author test scenario...${NC}"
    
    create_workspace_structure "testing"
    
    local authors=("alice@example.com" "bob@example.com" "charlie@example.com" "diana@example.com")
    local statuses=("draft" "review" "approved" "published")
    
    echo -e "${YELLOW}Generating ${COUNT} documents from multiple authors...${NC}"
    for i in $(seq 1 $COUNT); do
        local uuid=$(generate_uuid)
        local author="${authors[$((i % ${#authors[@]}))]}"
        local status="${statuses[$((i % ${#statuses[@]}))]}"
        
        # Stagger timestamps to simulate realistic creation times
        local days_ago=$((i % 30))
        local timestamp=$(date -u -v-${days_ago}d +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date -u -d "${days_ago} days ago" +"%Y-%m-%dT%H:%M:%SZ")
        
        local content=$(generate_rfc "$i" "$uuid" "Multi-author RFC ${i}" "$status" "$author" "$timestamp")
        write_document "${WORKSPACES_DIR}/testing/rfcs/RFC-$(printf "%03d" "$i")-multi-author.md" "$content"
        
        echo -e "${BLUE}  Created document ${i}: ${author} (${status}) ${timestamp}${NC}"
    done
    
    echo -e "${GREEN}✅ Multi-author scenario complete${NC}"
}

# Generate docs workspace content
generate_docs_content() {
    echo -e "${BLUE}Generating documentation content...${NC}"
    
    create_workspace_structure "docs"
    
    local docs_topics=("Getting Started" "Installation Guide" "API Reference" "Configuration" "Troubleshooting")
    
    for i in "${!docs_topics[@]}"; do
        local title="${docs_topics[$i]}"
        local uuid=$(generate_uuid)
        local slug=$(echo "$title" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
        local content=$(generate_doc_page "$title" "$uuid" "guide")
        
        write_document "${WORKSPACES_DIR}/docs/docs/${slug}.md" "$content"
    done
    
    echo -e "${GREEN}✅ Documentation content generated${NC}"
}

# Execute scenario
case $SCENARIO in
    basic)
        scenario_basic
        if [ "$WORKSPACE" = "all" ]; then
            generate_docs_content
        fi
        ;;
    migration)
        scenario_migration
        ;;
    conflict)
        scenario_conflict
        ;;
    multi-author)
        scenario_multi_author
        ;;
esac

# Summary
echo ""
echo -e "${GREEN}=== Seeding Complete ===${NC}"
echo -e "${GREEN}Workspace: ${WORKSPACE}${NC}"
echo -e "${GREEN}Documents generated: ${COUNT}${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo -e "  1. Ensure Hermes is running: ${BLUE}make up${NC}"
echo -e "  2. Wait for indexing (5 minutes) or check logs: ${BLUE}make logs-hermes${NC}"
echo -e "  3. Verify documents: ${BLUE}curl http://localhost:8001/api/v2/documents | jq${NC}"
echo -e "  4. Open web UI: ${BLUE}open http://localhost:4201${NC}"
echo ""
