# golangci-lint configuration for Hermes project
# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow  # Too many false positives

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - hugeParam

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/hashicorp-forge/hermes

  misspell:
    locale: US

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  staticcheck:
    checks: ["all"]

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]  # Disable some overly strict rules

  unused:
    check-exported: false

  unparam:
    check-exported: false

linters:
  disable-all: true
  enable:
    # Enabled by default
    - errcheck    # Check for unchecked errors
    - gosimple    # Simplify code suggestions
    - govet       # Go vet analysis
    - ineffassign # Detect ineffectual assignments
    - staticcheck # Staticcheck
    - typecheck   # Type checking
    - unused      # Check for unused code

    # Additional linters
    - gocyclo     # Check cyclomatic complexity
    - gocognit    # Check cognitive complexity
    - goconst     # Find repeated strings that could be constants
    - gocritic    # Comprehensive checks
    - gofmt       # Check formatting
    - goimports   # Check import organization
    - misspell    # Check for misspellings
    - revive      # Fast, configurable, extensible linter
    - stylecheck  # Style checks
    - unparam     # Find unused function parameters
    - unconvert   # Remove unnecessary type conversions
    - gosec       # Security checks
    - dupl        # Code clone detection
    - prealloc    # Find slice declarations that could potentially be preallocated

issues:
  exclude-dirs:
    - vendor
    - node_modules
    - web
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Exclude complexity checks for generated files
    - path: (.*)?_gen\.go
      linters:
        - gocyclo
        - gocognit

    # Exclude specific messages
    - text: "G404: Use of weak random number generator"
      linters:
        - gosec

    - text: "should have a package comment"
      linters:
        - revive
        - stylecheck

  max-issues-per-linter: 50
  max-same-issues: 10
  new: false
  fix: false
