#!/usr/bin/env bash
#
# document-generator.sh - Reusable document generation library
#
# Usage:
#   source ./lib/document-generator.sh
#   generate_rfc 1 "$(uuidgen)" "API Gateway Design"
#

set -e

# Color output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Generate UUID (cross-platform)
generate_uuid() {
    if command -v uuidgen &> /dev/null; then
        uuidgen | tr '[:upper:]' '[:lower:]'
    else
        # Fallback for systems without uuidgen
        python3 -c 'import uuid; print(str(uuid.uuid4()))'
    fi
}

# Generate current timestamp in ISO 8601 format
generate_timestamp() {
    date -u +"%Y-%m-%dT%H:%M:%SZ"
}

# Generate RFC document
# Args: number, uuid, title, [status], [author]
generate_rfc() {
    local number="$1"
    local uuid="${2:-$(generate_uuid)}"
    local title="${3:-Sample RFC}"
    local status="${4:-draft}"
    local author="${5:-test-user@example.com}"
    local created="${6:-$(generate_timestamp)}"
    
    cat <<EOF
---
hermes-uuid: ${uuid}
document-type: RFC
document-number: RFC-$(printf "%03d" "$number")
status: ${status}
title: "${title}"
authors:
  - ${author}
created: ${created}
modified: ${created}
tags:
  - rfc
  - testing
  - distributed
---

# RFC-$(printf "%03d" "$number"): ${title}

## Summary

This is a Request for Comments document for testing Hermes distributed indexing capabilities.

**Status**: ${status}  
**Author**: ${author}  
**Created**: ${created}

## Background

This document was automatically generated as part of the Hermes testing framework to validate:
- Document indexing from local workspaces
- UUID-based document identification
- Multi-provider document management
- Content hash tracking for drift detection

## Problem Statement

Testing distributed document authoring and indexing requires realistic sample documents that:
1. Follow the RFC template structure
2. Have stable UUIDs for cross-provider tracking
3. Contain searchable content
4. Support version tracking

## Proposal

Generate test documents with:
- YAML frontmatter including UUID
- Structured markdown content
- Realistic metadata (authors, dates, status)
- Searchable keywords and phrases

### Implementation Details

**Document Structure**:
- Frontmatter: YAML with required fields
- Body: Markdown with standard RFC sections
- Footer: References and metadata

**Indexing Requirements**:
- File type: \`.md\` (Markdown)
- Location: Workspace directories
- Scanner: Local workspace indexer
- Search: Meilisearch backend

### Example Usage

\`\`\`bash
# Generate RFC in testing workspace
./scripts/seed-workspaces.sh --type rfc --count 5

# Verify indexing
curl http://localhost:8001/api/v2/documents?type=rfc
\`\`\`

## Alternatives Considered

1. **Manual document creation** - Too time-consuming, not reproducible
2. **Copied templates** - Lacks variety, all look identical
3. **Lorem ipsum content** - Not realistic for search testing
4. **Generated content** - ✅ Chosen approach (this document)

## Security Considerations

This is **test data only**:
- Uses \`example.com\` email addresses
- Contains no real credentials or sensitive information
- UUIDs are randomly generated (not from production)
- Safe to commit to public repository

## Testing Impact

This document should:
- ✅ Be detected by local workspace indexer
- ✅ Be indexed in Meilisearch
- ✅ Appear in document search results
- ✅ Support UUID-based retrieval
- ✅ Track content hash for changes

## References

- **Generator Script**: \`testing/scripts/lib/document-generator.sh\`
- **Seed Script**: \`testing/scripts/seed-workspaces.sh\`
- **Architecture**: \`docs-internal/DISTRIBUTED_PROJECTS_ARCHITECTURE.md\`
- **Testing Guide**: \`testing/DISTRIBUTED_TESTING_ENHANCEMENTS.md\`

---

**Generated by**: Hermes Test Document Generator  
**Hermes UUID**: ${uuid}  
**Document Type**: RFC  
**Version**: 1.0.0
EOF
}

# Generate PRD document
# Args: number, uuid, title, [status], [author]
generate_prd() {
    local number="$1"
    local uuid="${2:-$(generate_uuid)}"
    local title="${3:-Sample Product Requirements}"
    local status="${4:-draft}"
    local author="${5:-product-manager@example.com}"
    local created="${6:-$(generate_timestamp)}"
    
    cat <<EOF
---
hermes-uuid: ${uuid}
document-type: PRD
document-number: PRD-$(printf "%03d" "$number")
status: ${status}
title: "${title}"
authors:
  - ${author}
created: ${created}
modified: ${created}
tags:
  - prd
  - product
  - requirements
  - testing
---

# PRD-$(printf "%03d" "$number"): ${title}

## Overview

**Status**: ${status}  
**Owner**: ${author}  
**Last Updated**: ${created}

This Product Requirements Document was generated for testing distributed Hermes workflows.

## Problem Statement

Users need a way to test Hermes document management with realistic PRD documents that:
- Follow standard PRD structure
- Include product features and requirements
- Support indexing and search
- Track versions via UUID

## Goals and Non-Goals

### Goals
- ✅ Validate PRD document type indexing
- ✅ Test metadata extraction from frontmatter
- ✅ Verify search across document types
- ✅ Support migration scenarios

### Non-Goals
- ❌ Production-ready feature specifications
- ❌ Real product decisions
- ❌ Actual implementation timelines

## User Stories

1. **As a developer**, I want test documents so I can validate indexing
2. **As a tester**, I want realistic PRDs to test search functionality
3. **As an operator**, I want sample data to verify distributed scenarios

## Requirements

### Functional Requirements

**FR-1: Document Structure**
- MUST have YAML frontmatter with UUID
- MUST follow PRD template format
- MUST include standard sections

**FR-2: Indexing**
- MUST be discoverable by local workspace scanner
- MUST be indexed in search backend
- MUST appear in API document list

**FR-3: Metadata**
- MUST track author information
- MUST include creation timestamp
- MUST support status tracking (draft, review, approved)

### Non-Functional Requirements

**NFR-1: Performance**
- Document generation < 1 second per document
- Indexing within 5 seconds of creation

**NFR-2: Scalability**
- Support generation of 100+ documents
- No performance degradation

## Technical Design

### Document Format
- **Type**: Markdown with YAML frontmatter
- **Location**: \`workspaces/testing/prds/\`
- **Naming**: \`PRD-NNN-kebab-case-title.md\`

### Indexing Flow
\`\`\`
1. Generator creates PRD file
2. File written to workspace directory
3. Indexer scans workspace (5-minute interval)
4. Document metadata extracted
5. Content indexed in Meilisearch
6. Document available via API
\`\`\`

## Success Metrics

- Documents generated without errors
- 100% indexing success rate
- Search returns expected results
- UUID-based retrieval works

## Timeline

- **Phase 1**: Document generator library ✅
- **Phase 2**: Seed script integration
- **Phase 3**: Scenario automation
- **Phase 4**: CI/CD integration

## Open Questions

- Q: Should we generate documents with version history?
- Q: How many documents per scenario?
- Q: Should we simulate document updates?

## References

- **Generator**: \`testing/scripts/lib/document-generator.sh\`
- **PRD Template**: Standard Hermes PRD format
- **Testing Docs**: \`testing/DISTRIBUTED_TESTING_ENHANCEMENTS.md\`

---

**Generated**: ${created}  
**UUID**: ${uuid}  
**Type**: PRD
EOF
}

# Generate meeting notes
# Args: number, uuid, title, [attendees], [date]
generate_meeting_notes() {
    local number="$1"
    local uuid="${2:-$(generate_uuid)}"
    local title="${3:-Team Sync}"
    local attendees="${4:-alice@example.com,bob@example.com,charlie@example.com}"
    local meeting_date="${5:-$(date -u +"%Y-%m-%d")}"
    local created="${6:-$(generate_timestamp)}"
    
    cat <<EOF
---
hermes-uuid: ${uuid}
document-type: MEETING
document-number: MEET-$(printf "%03d" "$number")
title: "${title}"
meeting-date: ${meeting_date}
attendees:
  - alice@example.com
  - bob@example.com
  - charlie@example.com
created: ${created}
modified: ${created}
tags:
  - meeting
  - notes
  - testing
---

# Meeting Notes: ${title}

**Date**: ${meeting_date}  
**Time**: 10:00 AM - 11:00 AM UTC  
**Location**: Virtual / Zoom  
**Attendees**: ${attendees}

## Agenda

1. Distributed testing infrastructure updates
2. Document indexing performance review
3. Migration scenario validation
4. Action items from previous meeting

## Discussion

### Topic 1: Distributed Testing Infrastructure

**Summary**: Team reviewed the current state of distributed testing for Hermes.

**Key Points**:
- Multiple indexers now supported via Docker profiles
- Seed data generation working well
- Need more migration scenario tests

**Decisions**:
- ✅ Proceed with multi-indexer testing
- ✅ Add conflict detection scenarios
- ⏳ Monitor performance with 100+ documents

### Topic 2: Indexing Performance

**Metrics Reviewed**:
- Current scan interval: 5 minutes
- Average indexing time: 2 seconds per document
- Search latency: <100ms for 50 documents

**Action Items**:
- [ ] Benchmark with 500 documents
- [ ] Optimize scan interval
- [ ] Add monitoring dashboard

### Topic 3: Migration Scenarios

**Progress Update**:
- UUID tracking implemented
- Content hash comparison working
- Need conflict resolution UI

**Blockers**:
- None currently

### Topic 4: Previous Action Items

- ✅ Set up multi-indexer docker-compose profiles
- ✅ Create document generator library
- ⏳ Add E2E playwright tests (in progress)
- ⏳ Performance benchmarking (blocked on large dataset)

## Action Items

1. **@alice** - Complete E2E playwright tests for distributed workflows (Due: Oct 30)
2. **@bob** - Set up monitoring dashboard (Due: Oct 27)
3. **@charlie** - Generate 500-document test dataset (Due: Oct 25)
4. **@team** - Review migration conflict detection PR

## Next Meeting

**Date**: ${meeting_date} + 7 days  
**Agenda**:
- Performance benchmark results
- E2E test coverage review
- Migration conflict resolution demo

---

**Generated**: ${created}  
**UUID**: ${uuid}  
**Type**: MEETING
EOF
}

# Generate documentation page
# Args: title, uuid, category, [author]
generate_doc_page() {
    local title="$1"
    local uuid="${2:-$(generate_uuid)}"
    local category="${3:-guide}"
    local author="${4:-docs-team@example.com}"
    local created="${5:-$(generate_timestamp)}"
    
    echo "---"
    echo "hermes-uuid: ${uuid}"
    echo "document-type: DOCUMENTATION"
    echo "title: \"${title}\""
    echo "category: ${category}"
    echo "author: ${author}"
    echo "created: ${created}"
    echo "modified: ${created}"
    echo "public: true"
    echo "tags:"
    echo "  - documentation"
    echo "  - ${category}"
    echo "  - testing"
    echo "---"
    echo ""
    echo "# ${title}"
    echo ""
    echo "**Category**: ${category}"
    echo "**Last Updated**: ${created}"
    echo ""
    echo "## Introduction"
    echo ""
    echo "This documentation page was generated for testing Hermes distributed content management capabilities."
    echo ""
    echo "## Overview"
    echo ""
    echo "Hermes supports multiple document types including RFC, PRD, FRD, MEETING, and DOCUMENTATION."
    echo ""
    echo "## Getting Started"
    echo ""
    echo "For detailed instructions, see the main Hermes documentation."
    echo ""
    echo "---"
    echo ""
    echo "**UUID**: ${uuid}"
    echo "**Generated**: ${created}"
    echo "**Type**: DOCUMENTATION"
}

# Helper: Create directory if it doesn't exist
ensure_dir() {
    local dir="$1"
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
        echo -e "${BLUE}Created directory: ${dir}${NC}"
    fi
}

# Helper: Write document to file
write_document() {
    local filepath="$1"
    local content="$2"
    
    # Ensure parent directory exists
    ensure_dir "$(dirname "$filepath")"
    
    # Write content
    echo "$content" > "$filepath"
    
    echo -e "${GREEN}✅ Generated: ${filepath}${NC}"
}
